name: CI (conda, multi-python)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Create conda env
        shell: bash -l {0}
        run: |
          conda create -y -n airs-test python=${{ matrix.python-version }} pip pytest
          conda activate airs-test
          conda info
          python -V

      - name: Install minimal deps (no heavy deps)
        shell: bash -l {0}
        run: |
          conda activate airs-test
          # minimal libs for light tests
          python -m pip install --upgrade pip
          python -m pip install pillow

      - name: Run tests (lightweight subset)
        shell: bash -l {0}
        run: |
          conda activate airs-test
          export PYTHONPATH=$GITHUB_WORKSPACE
          # Run only lightweight tests that do not require models or torch
          pytest -q quality/tests/services
