name: Publish Node package to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure GitHub Packages scope
        run: |
          echo "@nathanrish:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install (noop for UXP panel)
        working-directory: frontend
        run: npm ci --ignore-scripts || true

      - name: Publish to GitHub Packages
        working-directory: frontend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --access public
